In [1]:
import pandas as pd

# Load the dataset
file_path = "gastric_cancer_data.csv"
df = pd.read_csv(file_path)

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212354 entries, 0 to 212353
Data columns (total 29 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   age                            212354 non-null  int64
 1   gender                         212354 non-null  object
 2   ethnicity                      212354 non-null  object
 3   geographical_location          212354 non-null  object
 4   family_history                 212354 non-null  int64
 5   smoking_habits                 212354 non-null  int64
 6   alcohol_consumption            212354 non-null  int64
 7   helicobacter_pylori_infection  212354 non-null  int64
 8   dietary_habits                 212354 non-null  object
 9   existing_conditions            169868 non-null  object
 10  endoscopic_images              212354 non-null  object
 11  biopsy_results                 212354 non-null  object
 12  ct_scan                        212354 non-null  object
 13  mature_mirna_acc               212354 non-null  object
 14  mature_mirna_id                212354 non-null  object
 15  target_symbol                  212354 non-null  object
 16  target_entrez                  212354 non-null  int64
 17  target_ensembl                 212354 non-null  int64
 18  diana_microt                   212354 non-null  float64
 19  elmmo                          212354 non-null  float64
 20  microcosm                      212354 non-null  float64
 21  miranda                        212354 non-null  float64
 22  mirdb                          212354 non-null  float64
 23  pictar                         212354 non-null  float64
 24  pita                           212354 non-null  float64
 25  targetscan                     212354 non-null  float64
 26  predicted.sum                  212354 non-null  float64
 27  all.sum                        212354 non-null  float64
 28  label                          212354 non-null  int64
dtypes: float64(10), int64(8), object(11)
memory usage: 47.0+ MB

In [3]:
df.head()

,age,gender,ethnicity,geographical_location,family_history,smoking_habits,alcohol_consumption,helicobacter_pylori_infection,dietary_habits,existing_conditions,...,elmmo,microcosm,miranda,mirdb,pictar,pita,targetscan,predicted.sum,all.sum,label
0,43,Male,Ethnicity_A,Other,1,0,0,0,Low_Salt,Chronic Gastritis,...,0.187003,0.786422,0.204816,0.561920,0.438175,0.283603,0.928244,4.324299,7.666791,0
1,86,Female,Ethnicity_B,California,1,0,0,1,High_Salt,Diabetes,...,0.493322,0.963989,0.498041,0.985585,0.144609,0.375375,0.103573,7.967674,1.483280,0
2,68,Male,Ethnicity_A,California,0,1,1,0,High_Salt,NaN,...,0.573560,0.666896,0.540388,0.905853,0.827279,0.350915,0.166878,3.748651,3.046783,0
3,57,Female,Ethnicity_A,Other,0,0,0,1,High_Salt,Chronic Gastritis,...,0.261399,0.949488,0.134170,0.429935,0.935231,0.794704,0.867036,5.478298,8.811307,0
4,33,Male,Ethnicity_A,California,0,1,1,0,High_Salt,Diabetes,...,0.754478,0.263164,0.876767,0.650832,0.337669,0.427492,0.915804,1.809181,0.394632,0

In [4]:
# categorical columns
categorical_cols = df.select_dtypes(include=["object"]).columns

In [5]:
from sklearn.preprocessing import LabelEncoder

# apply label encoding 
label_encoders = {}
for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

In [6]:
df

,age,gender,ethnicity,geographical_location,family_history,smoking_habits,alcohol_consumption,helicobacter_pylori_infection,dietary_habits,existing_conditions,...,elmmo,microcosm,miranda,mirdb,pictar,pita,targetscan,predicted.sum,all.sum,label
0,43,1,0,1,1,0,0,0,1,0,...,0.187003,0.786422,0.204816,0.561920,0.438175,0.283603,0.928244,4.324299,7.666791,0
1,86,0,1,0,1,0,0,1,0,1,...,0.493322,0.963989,0.498041,0.985585,0.144609,0.375375,0.103573,7.967674,1.483280,0
2,68,1,0,0,0,1,1,0,0,2,...,0.573560,0.666896,0.540388,0.905853,0.827279,0.350915,0.166878,3.748651,3.046783,0
3,57,0,0,1,0,0,0,1,0,0,...,0.261399,0.949488,0.134170,0.429935,0.935231,0.794704,0.867036,5.478298,8.811307,0
4,33,1,0,0,0,1,1,0,0,1,...,0.754478,0.263164,0.876767,0.650832,0.337669,0.427492,0.915804,1.809181,0.394632,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212349,47,1,0,0,0,1,1,0,0,0,...,0.408123,0.925035,0.267628,0.538474,0.463471,0.827892,0.929147,0.866260,6.698303,0
212350,59,0,0,0,0,1,1,0,0,0,...,0.578204,0.768279,0.339168,0.236523,0.444216,0.011762,0.053098,5.102216,2.338017,0
212351,58,0,2,0,0,0,0,0,0,2,...,0.940936,0.865221,0.448189,0.899351,0.766615,0.098454,0.384019,7.774612,4.601637,1
212352,77,0,1,0,1,1,0,1,0,0,...,0.498088,0.048195,0.924610,0.101521,0.464988,0.639401,0.410327,2.362698,2.020047,0
212353,71,1,0,0,0,0,0,1,0,2,...,0.689696,0.701524,0.250955,0.102458,0.077025,0.463766,0.765164,2.392974,4.487878,0

In [ ]:
df.to_csv("encoded_gastric_cancer_data.csv", index=False)

In [9]:
test_df = df.head(1000)

In [10]:
test_df.to_csv("1000_encoded_gastric_cancer_data.csv", index=False)